preinstall change nginx.conf

diff --git a/DEBIAN/preinst b/DEBIAN/preinst
--- a/DEBIAN/preinst
+++ b/DEBIAN/preinst
@@ -3,10 +3,21 @@
 ORIGINAL_PHP_INI='/etc/php/8.1/cli/php.ini'
 CUSTOM_PHP_INI='./custom_files/php.ini'
 
-if [ -f '$ORIGINAL_PHP_INI' ]; then
+if [ -f '$CUSTOM_PHP_INI' ]; then
     cp '$CUSTOM_PHP_INI' '$ORIGINAL_PHP_INI'
     echo 'Custom php.ini copied successfully.'
 else
-    echo 'Original php.ini not found. Custom php.ini not copied.'
+    echo 'Custom php.ini not found. Not copied.'
+    exit 1
+fi
+
+ORIGINAL_NGINX_CONF='/etc/nginx/nginx.conf'
+CUSTOM_NGINX_CONF='./custom_files/nginx.conf'
+
+if [ -f '$CUSTOM_NGINX_CONF' ]; then
+    cp '$CUSTOM_NGINX_CONF' '$ORIGINAL_NGINX_CONF'
+    echo 'Custom nginx.conf copied successfully.'
+else
+    echo 'Custom nginx.conf not found. Not copied.'
     exit 1
 fi
